package application_test

import (
	"bytes"
	"encoding/json"
	"os"
	"testing"

	"github.com/shopspring/decimal"

	"github.com/lidp280504357/exchange/internal/instrument/application"
	"github.com/lidp280504357/exchange/internal/instrument/domain"
)

// The deployed reference data (deploy/instruments/test.json, generated by
// gen-top50.go) must pass what apply checks, without a database: every
// asset valid, every pair valid against its assets, the internal assets
// without deposits or withdrawals (ADR-0013), 1000x coins mapped
// (ADR-0014).
func TestTheDeployedReferenceDataIsValid(t *testing.T) {
	raw, err := os.ReadFile("../../../deploy/instruments/test.json")
	if err != nil {
		t.Fatal(err)
	}
	var cfg application.Config
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&cfg); err != nil {
		t.Fatal(err)
	}
	assets := map[string]domain.Asset{}
	for _, a := range cfg.Assets {
		if err := a.Validate(); err != nil {
			t.Fatalf("asset %s: %v", a.Code, err)
		}
		if a.Code != "USDT" && a.Code != "BTC" && a.Code != "ETH" && (a.DepositEnabled || a.WithdrawEnabled || len(a.Networks) > 0) {
			t.Errorf("internal asset %s has deposits, withdrawals or networks", a.Code)
		}
		assets[a.Code] = a.Asset
	}
	usdt, seen := 0, map[string]bool{}
	for _, p := range cfg.Pairs {
		if seen[p.Symbol] {
			t.Errorf("pair %s listed twice", p.Symbol)
		}
		seen[p.Symbol] = true
		if p.ReferenceMultiplier.IsZero() {
			p.ReferenceMultiplier = p.ReferenceMultiplier.Add(one)
		}
		base, quote := assets[p.BaseAsset], assets[p.QuoteAsset]
		if err := p.Validate(base, quote); err != nil {
			t.Errorf("pair %s: %v", p.Symbol, err)
		}
		if p.QuoteAsset == "USDT" {
			usdt++
			// The platform coin's market is its own (ASTRA design §2).
			if p.ReferenceSymbol == "" && p.BaseAsset != "ASTRA" {
				t.Errorf("pair %s follows no reference market", p.Symbol)
			}
		}
		if len(p.BaseAsset) > 4 && p.BaseAsset[:4] == "1000" && !p.ReferenceMultiplier.Equal(thousand) {
			t.Errorf("pair %s is 1000x without the multiplier", p.Symbol)
		}
	}
	// The top 50 and the 2026-10-02 extension (the coins Binance trades).
	if usdt < 50 {
		t.Fatalf("%d USDT pairs, want the top 50 at least", usdt)
	}
}

var (
	one      = decimal.NewFromInt(1)
	thousand = decimal.NewFromInt(1000)
)
