package application_test

import (
	"bytes"
	"encoding/json"
	"os"
	"testing"

	"github.com/shopspring/decimal"

	"github.com/skill/exchange/internal/instrument/application"
	"github.com/skill/exchange/internal/instrument/domain"
)

// The deployed reference data (deploy/instruments/test.json, generated by
// gen-top50.go) must pass what apply checks, without a database: every
// asset valid, every pair valid against its assets, the internal assets
// without deposits or withdrawals (ADR-0013), 1000x coins mapped
// (ADR-0014), the hidden test asset TUSD only on the stand-in custodian
// and without pairs (ADR-0017).
func TestTheDeployedReferenceDataIsValid(t *testing.T) {
	raw, err := os.ReadFile("../../../deploy/instruments/test.json")
	if err != nil {
		t.Fatal(err)
	}
	var cfg application.Config
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&cfg); err != nil {
		t.Fatal(err)
	}
	assets := map[string]domain.Asset{}
	for _, a := range cfg.Assets {
		if err := a.Validate(); err != nil {
			t.Fatalf("asset %s: %v", a.Code, err)
		}
		for _, n := range a.Networks {
			n.AssetCode = a.Code
			if err := n.Validate(a.Asset); err != nil {
				t.Errorf("network %s/%s: %v", a.Code, n.Network, err)
			}
			if a.Hidden != (n.Provider == domain.ProviderUdunMock) {
				t.Errorf("network %s/%s: the stand-in custodian serves the hidden test asset alone", a.Code, n.Network)
			}
		}
		switch {
		case a.Hidden && a.Code != "TUSD":
			t.Errorf("hidden asset %s: TUSD is the end-to-end tests' only one", a.Code)
		case a.Hidden:
		case a.Code != "USDT" && a.Code != "BTC" && a.Code != "ETH" && (a.DepositEnabled || a.WithdrawEnabled || len(a.Networks) > 0):
			t.Errorf("internal asset %s has deposits, withdrawals or networks", a.Code)
		}
		assets[a.Code] = a.Asset
	}
	if !assets["TUSD"].Hidden {
		t.Error("TUSD, the end-to-end tests' hidden asset, is missing")
	}
	usdt, seen := 0, map[string]bool{}
	for _, p := range cfg.Pairs {
		if seen[p.Symbol] {
			t.Errorf("pair %s listed twice", p.Symbol)
		}
		seen[p.Symbol] = true
		if p.ReferenceMultiplier.IsZero() {
			p.ReferenceMultiplier = p.ReferenceMultiplier.Add(one)
		}
		base, quote := assets[p.BaseAsset], assets[p.QuoteAsset]
		if err := p.Validate(base, quote); err != nil {
			t.Errorf("pair %s: %v", p.Symbol, err)
		}
		if p.QuoteAsset == "USDT" {
			usdt++
			// The platform coin's market is its own (ASTRA design §2).
			if p.ReferenceSymbol == "" && p.BaseAsset != "ASTRA" {
				t.Errorf("pair %s follows no reference market", p.Symbol)
			}
		}
		if len(p.BaseAsset) > 4 && p.BaseAsset[:4] == "1000" && !p.ReferenceMultiplier.Equal(thousand) {
			t.Errorf("pair %s is 1000x without the multiplier", p.Symbol)
		}
	}
	// The top 50 and the 2026-10-02 extension (the coins Binance trades).
	if usdt < 50 {
		t.Fatalf("%d USDT pairs, want the top 50 at least", usdt)
	}
	// Every contract valid against its assets, on a listed USDT pair, once;
	// a coin-margined one beside a linear one on its coin (design
	// 2026-10-06 §2.1, §3.4: Binance's lists, gen-contracts.go).
	kinds, listed := map[string]map[string]bool{}, map[string]bool{}
	for _, c := range cfg.Contracts {
		c = c.WithDefaults()
		if err := c.Validate(assets[c.BaseAsset], assets[c.PriceAsset()]); err != nil {
			t.Errorf("contract %s: %v", c.Symbol, err)
		}
		if listed[c.Symbol] {
			t.Errorf("contract %s listed twice", c.Symbol)
		}
		listed[c.Symbol] = true
		if !seen[c.IndexSymbol] {
			t.Errorf("contract %s: its index %s is not a listed pair", c.Symbol, c.IndexSymbol)
		}
		if kinds[c.BaseAsset] == nil {
			kinds[c.BaseAsset] = map[string]bool{}
		}
		kinds[c.BaseAsset][c.MarginType] = true
		if c.BaseAsset != "ASTRA" && c.ReferenceSymbol == "" {
			t.Errorf("contract %s follows no Binance contract", c.Symbol)
		}
	}
	for base, k := range kinds {
		if k[domain.MarginCoin] && !k[domain.MarginUSDT] {
			t.Errorf("%s: a coin-margined contract without a linear one", base)
		}
	}
}

var (
	one      = decimal.NewFromInt(1)
	thousand = decimal.NewFromInt(1000)
)
